[package]
name = "eve-engines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
eve-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
walkdir.workspace = true
rayon.workspace = true
glob.workspace = true
libc.workspace = true
sysinfo.workspace = true
eve-catalog.workspace = true

[dev-dependencies]
tempfile = "3"
